import type { Metadata } from 'next'
import { StarknetProvider } from "../components/starknet-provider";
 
// These styles apply to every route in the application
import '../../styles/globals.css'
 
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <StarknetProvider>
      <body>{children}</body>
      </StarknetProvider>
    </html>
  )
}